"""
Offline logic tests for collect_developer_adoption.py.

!!! ALL DATA HERE IS SYNTHETIC (generated by formulas below) and is written only to a temporary directory. !!!
!!! It exists solely to prove the code behaves correctly. It is NOT Datadog / PyPI / npm data.            !!!

Run:  python test_offline_pipeline.py      (or: pytest -q test_offline_pipeline.py)
"""
import datetime as dt, json, re, tempfile, os, types
import numpy as np, pandas as pd
import collect_developer_adoption as C

# ------------------------------------------------------------------ synthetic generators
SPIKE_DAY = dt.date(2023, 5, 17)                      # a Wednesday: injected 6x spike in the fake npm series
GAP_DAYS = {dt.date(2023, 5, 10), dt.date(2023, 5, 11), dt.date(2023, 5, 12)}   # absent from the fake PyPI source

def qidx(d): return (d.year - 2021) * 4 + (d.month - 1) // 3
def npm_val(d):
    base = 1000 * 1.08 ** qidx(d) * (0.5 if d.weekday() >= 5 else 1.0)
    return int(round(base * (6 if d == SPIKE_DAY else 1)))
def py_val(d):
    return int(round(400 * 1.05 ** qidx(d) * (0.8 if d.weekday() >= 5 else 1.0)))
def daterange(a, b):
    while a <= b: yield a; a += dt.timedelta(days=1)

class Resp:
    def __init__(self, obj, url="mock"):
        self._o, self.url, self.content, self.text = obj, url, json.dumps(obj).encode(), json.dumps(obj)
    def json(self): return self._o

class FakeHttp:
    def __init__(self, trim=False): self.log, self.trim, self.calls = [], trim, []
    def request(self, method, url, params=None, data=None, **kw):
        self.calls.append((method, url))
        m = re.search(r"/downloads/(range|point)/(\d{4}-\d\d-\d\d):(\d{4}-\d\d-\d\d)/(.+)$", url)
        if m:
            kind, a, b = m.group(1), dt.date.fromisoformat(m.group(2)), dt.date.fromisoformat(m.group(3))
            days = [{"day": str(d), "downloads": npm_val(d)} for d in daterange(a, b)]
            if kind == "point": return Resp({"downloads": sum(x["downloads"] for x in days), "start": str(a), "end": str(b), "package": m.group(4)})
            start = str(a + dt.timedelta(days=1)) if self.trim else str(a)          # simulate npm silently trimming a window
            return Resp({"downloads": days, "start": start, "end": str(b), "package": m.group(4)})
        if url == C.CLICKHOUSE_URL:
            sql = data.decode()
            if "system.columns" in sql: return Resp({"data": [["date"], ["project"], ["count"]]})
            a, b = re.findall(r"'(\d{4}-\d\d-\d\d)'", sql)
            rows = [[str(d), py_val(d)] for d in daterange(dt.date.fromisoformat(a), dt.date.fromisoformat(b)) if d not in GAP_DAYS]
            return Resp({"data": rows})
        if "pypistats.org" in url:
            d0 = dt.date(2026, 1, 1)
            return Resp({"data": [{"category": "with_mirrors", "date": str(d), "downloads": py_val(d)} for d in daterange(d0, d0 + dt.timedelta(days=60))]})
        if url.startswith("https://registry.npmjs.org/"):
            return Resp({"time": {"created": "2018-02-28T00:00:00.000Z", "modified": "2026-06-01T00:00:00.000Z", "1.0.0": "2023-05-16T12:00:00.000Z", "1.1.0-beta.1": "2023-01-01T00:00:00.000Z", "2.0.0": "2024-02-02T00:00:00.000Z"},
                         "dist-tags": {"latest": "2.0.0", "legacy": "1.0.0"}})
        if url.startswith("https://pypi.org/pypi/"):
            return Resp({"releases": {"1.0.0": [{"upload_time_iso_8601": "2022-03-01T12:00:00.000000Z"}], "2.0.0rc1": [{"upload_time_iso_8601": "2023-09-01T12:00:00.000000Z"}]}})
        raise AssertionError("unexpected URL in test: " + url)

def args(out): return C.parse_args(["--out-dir", out])

# ------------------------------------------------------------------ tests
def test_windows_cover_range_without_gaps_or_overlap():
    a, b = dt.date(2021, 1, 1), dt.date(2026, 6, 30)
    w = list(C.date_windows(a, b, C.NPM_MAX_DAYS))
    assert w[0][0] == a and w[-1][1] == b
    for (s1, e1), (s2, e2) in zip(w[:-1], w[1:]): assert s2 == e1 + dt.timedelta(days=1)
    assert all((e - s).days + 1 <= C.NPM_MAX_DAYS for s, e in w)
    assert sum((e - s).days + 1 for s, e in w) == (b - a).days + 1

def test_npm_fetch_full_and_verified():
    s, checks = C.fetch_npm_daily(FakeHttp(), "dd-trace", dt.date(2021, 1, 1), dt.date(2022, 12, 31))
    assert len(s) == 730 and s.index.is_unique and all(c["match"] for c in checks) and len(checks) == 2

def test_npm_trimmed_window_is_refused():
    try: C.fetch_npm_daily(FakeHttp(trim=True), "dd-trace", dt.date(2021, 1, 1), dt.date(2021, 6, 30))
    except RuntimeError as e: assert "different window" in str(e)
    else: raise AssertionError("trimmed window must raise")

def test_pipeline_end_to_end():
    with tempfile.TemporaryDirectory() as tmp:
        out, raw, qa = C.run(args(tmp), http=FakeHttp())
        # ---- exact output schemas
        q = pd.read_csv(os.path.join(tmp, "developer_adoption_quarterly.csv"))
        r = pd.read_csv(os.path.join(tmp, "developer_adoption_raw.csv"))
        assert list(q.columns) == ["Quarter", "PyPI_ddtrace_Downloads", "PyPI_Download_YoY", "NPM_ddtrace_Downloads", "NPM_Download_YoY"]
        assert list(r.columns) == ["Date", "ddtrace_Python_Downloads", "dd-trace_NPM_Downloads"]
        assert len(q) == 22 and q.Quarter.iloc[0] == "2021 Q1" and q.Quarter.iloc[-1] == "2026 Q2"
        assert len(r) == (dt.date(2026, 6, 30) - dt.date(2021, 1, 1)).days + 1
        # ---- no YoY where t-4 is unavailable (all four 2021 quarters), YoY present from 2022 Q1
        assert q.loc[q.Quarter.str.startswith("2021"), ["PyPI_Download_YoY", "NPM_Download_YoY"]].isna().all().all()
        assert q.loc[q.Quarter == "2022 Q1", ["PyPI_Download_YoY", "NPM_Download_YoY"]].notna().all().all()
        # ---- YoY arithmetic verified against an independent brute-force computation
        def qsum(f, y, qn):
            a = dt.date(y, 3 * qn - 2, 1); b = (dt.date(y + (qn == 4), (3 * qn) % 12 + 1, 1) - dt.timedelta(days=1))
            return sum(f(d) for d in daterange(a, b) if d not in (GAP_DAYS if f is py_val else set()))
        exp = (qsum(npm_val, 2024, 1) / qsum(npm_val, 2023, 1) - 1) * 100
        got = q.loc[q.Quarter == "2024 Q1", "NPM_Download_YoY"].iloc[0]
        assert abs(got - exp) < 0.01, (got, exp)
        # ---- gap handling: NOTHING filled. The 3 missing PyPI days blank the quarter and every YoY that uses it.
        assert pd.isna(q.loc[q.Quarter == "2023 Q2", "PyPI_ddtrace_Downloads"].iloc[0])
        assert pd.isna(q.loc[q.Quarter == "2023 Q2", "PyPI_Download_YoY"].iloc[0])
        assert pd.isna(q.loc[q.Quarter == "2024 Q2", "PyPI_Download_YoY"].iloc[0])          # base quarter (t-4) is blank
        assert q.loc[q.Quarter == "2023 Q3", "PyPI_Download_YoY"].notna().iloc[0]
        gap_rows = r[r.Date.isin([str(d) for d in GAP_DAYS])]
        assert len(gap_rows) == 3 and gap_rows["ddtrace_Python_Downloads"].isna().all()      # blank, not 0, not interpolated
        # ---- outlier is flagged in the QA report but NOT removed from the data
        assert int(r.loc[r.Date == str(SPIKE_DAY), "dd-trace_NPM_Downloads"].iloc[0]) == npm_val(SPIKE_DAY)
        rep = open(os.path.join(tmp, "developer_adoption_qa_report.md")).read()
        assert str(SPIKE_DAY) in rep and "1.0.0" in rep                                       # spike listed, tied to the nearby fake release
        assert "2023-05-10" in rep                                                            # gap listed
        meta = json.load(open(os.path.join(tmp, "developer_adoption_sources.json")))
        assert meta["npm"]["windows"] >= 5 and all(c["match"] for c in meta["npm"]["point_checks"])

def test_spike_detector_flags_injected_spike_only():
    idx = pd.date_range("2022-01-01", "2023-12-31", freq="D")
    s = pd.Series([npm_val(d.date()) for d in idx], index=idx, dtype="float64")
    t, _ = C.spike_table(s, None)
    assert SPIKE_DAY in list(t["date"]) and len(t) <= 3

def test_zero_base_yoy_guard():
    q = pd.DataFrame({"downloads": [0, 5, 5, 5, 10.0, np.nan]}); q = C.add_yoy(q)
    assert pd.isna(q.yoy_pct.iloc[4]) and pd.isna(q.yoy_pct.iloc[5])

def test_weekend_ratio_recovers_synthetic_pattern():
    idx = pd.date_range("2023-01-02", "2023-12-31", freq="D")
    s = pd.Series([npm_val(d.date()) if d.date() != SPIKE_DAY else 0 for d in idx], index=idx, dtype="float64")
    w = C.weekend_ratio_by_year(s.replace(0, np.nan))
    assert 0.45 < float(w.weekend_over_weekday.iloc[0]) < 0.55

if __name__ == "__main__":
    tests = [v for k, v in sorted(globals().items()) if k.startswith("test_") and callable(v)]
    for t in tests: t(); print("PASS", t.__name__)
    print(f"\n{len(tests)}/{len(tests)} offline logic tests passed (synthetic data, temp directory only).")
